remote_theme: jekyll/minima
plugins:
- jekyll-feed
- jekyll-remote-theme

minima:
  skin: dark
  
  # generate social links in footer
  social_links:
    github: soupbowl
    rss: rss

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

title: "Soupbowl's Speakeasy"
  #author:
  #  name: soupbowl
description: "FreeBSD and other IT guides."

show_excerpts: true

header_pages:
  - _pages/frontpage.md
  - _pages/about.md
  - _pages/archive.md

include:
  - _pages

exclude: 
    - .gitignore
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
