remote_theme: jekyll/minima
plugins:
- jekyll-feed
- jekyll-remote-theme

minima:
  skin: dark

  # generate social links in footer
  social_links:
    github: soupbowl

title: "Soupbowl's Speakeasy"
  #author:
  #  name: soupbowl
description: "FreeBSD and other IT guides."

show_excerpts: true

header_pages:
  - _pages/frontpage.md
  - _pages/about.md
  - _pages/archive.md

include:
  - _pages

exclude: 
    - .gitignore
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
